from .auth import router as auth_router
from .user import router as user_router
from .audit import router as audit_router
from .editor import router as editor_router
from .premises import router as premises_router
from .templates import router as templates_router
from .roles import router as roles_router
from .report import router as reports_router
from .category import router as categories_router
from .question import router as question_router
